Update cadastro.jsp
AmigosDeJesus/Extend pull request #19
Opened 2017-05-26 15:51 UTC by caioromao

Correções acerca de nomes de botões e opções da combo box.
#8

2017-05-26 20:08 UTC, Eddyosos requested changes
Ficou bom, mas ta duplicado, observe que o menu aparece duas vezes.

Tu esqueceu de deletar o que ja tinha?

2017-05-26 20:11 UTC, Eddyosos commented
Também observe que a parte de imagem (o gráfico) deveria ser selecionável (o usuário pode escolher entre N diferentes formas de apresentar o sensor)

2017-05-26 20:17 UTC, caioromao commented
Sim, acredito que esqueci de deletar o que ja tinha.

Sobre o gráfico, não sabia que seria uma seleção entre vários tipos...Vamos arrumar isso aí então

2017-05-31 17:52 UTC, Eddyosos approved these changes

2017-05-31 17:53 UTC, merged